spring:
  application:
    name: household-server
  datasource:
    url: jdbc:postgresql://localhost:5432/household
    username: household
    password: household
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: Asia/Seoul

server:
  port: 8080
